<template>
    <div :id="spec.id || cid" class="card-body" @click="openSpecimen">
        <Thumbnail :query="spec.query" />
        <div class="card-title-box">
            <div>
                <h5 class="card-title">
                    <SpecimenTitle :spec />
                </h5>
                <p v-safe-html="spec.subtitle" class="card-text" />
            </div>
            <div
                v-if="spec.canDelete"
                style="padding-right: 15px"
                @click.stop="deleteSpecimen">
                <span class="delete-button material-icons-sharp">
                    delete
                </span>
            </div>
        </div>
    </div>
</template>

<script lang="ts">
    import {defineComponent} from 'vue'
    import type {PropType} from 'vue'

    import SpecimenTitle from './SpecimenTitle.vue'
    import Thumbnail from './Thumbnail.vue'

    import {addSequence} from '@/shared/browserCaching'
    import {parseSpecimenQuery} from '@/shared/specimenEncoding'

    export interface CardSpecimen {
        query: string
        id?: string // defaults to SC-NNNN, autogenerated serial number NNNN
        title?: string // defaults to the name encoded in the query
        subtitle: string
        lastEdited?: string
        canDelete?: boolean // if not present defaults to false
    }

    let cid_count = 0

    export default defineComponent({
        name: 'SpecimenCard',
        components: {
            SpecimenTitle,
            Thumbnail,
        },
        props: {
            spec: {type: Object as PropType<CardSpecimen>, required: true},
            cid: {
                type: String,
                default: function () {
                    return 'SC-' + cid_count++
                },
            },
        },
        emits: ['specimenDeleted', 'selected'],
        methods: {
            openSpecimen() {
                const {sequenceKind, sequenceQuery} = parseSpecimenQuery(
                    this.spec.query
                )
                addSequence(sequenceKind, sequenceQuery)
                this.$router.push(`/?${this.spec.query}`)
                this.$emit('selected')
            },
            deleteSpecimen() {
                this.$emit('specimenDeleted')
            },
        },
    })
</script>

<style scoped>
    .card-body {
        position: relative;
        width: var(--ns-specimen-card-width);
        border: 1px solid var(--ns-color-black);
        display: flex;
        flex-direction: column;
        align-items: center;
        cursor: pointer;
    }
    .high-card {
        background-color: var(--ns-color-primary);
    }
    .fade-card {
        background-color: var(--ns-color-white);
        transition: background-color 2s linear;
    }
    .card-title-box {
        width: 100%;
        border-top: 1px solid var(--ns-color-black);
        align-items: left;
        text-align: left;
        display: flex;
        align-items: start;
        justify-content: space-between;
    }
    .card-title {
        font-size: 14px;
        font-weight: var(--ns-font-weight-medium);
        margin-left: 8px;
        margin-bottom: 2px;
        margin-top: 8px;

        a {
            color: var(--ns-color-grey);
            .info {
                transform: scale(0.6);
            }
            .info:hover {
                transform: scale(0.75);
            }
        }
        a:hover {
            color: var(--ns-color-black);
        }
    }
    .card-text {
        font-size: 12px;
        margin-top: 2px;
        margin-left: 8px;
        margin-right: 8px;
        margin-bottom: 8px;
        color: #6c757d;
    }
    .delete-button {
        user-select: none;
        margin-top: 1ex;
        color: var(--ns-color-grey);
        &:hover {
            color: var(--ns-color-black);
        }
    }
</style>
