#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run lint:list || echo 'Files listed above will be reformatted and staged.'
npm run lint:staged
npm run lint:check
npm run typecheck
npm run test:unit
npm run test:e2e -- --reporter dot
